// One type per distinct attribute name used in `elements.rs`.
// `name = "html-name"` where the Rust identifier differs from the HTML name.
attr_keys! {
    abbr,
    accept,
    accept_charset = "accept-charset",
    accesskey,
    action,
    allow,
    allowfullscreen,
    allowpaymentrequest,
    alt,
    aria_activedescendant = "aria-activedescendant",
    aria_atomic = "aria-atomic",
    aria_autocomplete = "aria-autocomplete",
    aria_busy = "aria-busy",
    aria_checked = "aria-checked",
    aria_colcount = "aria-colcount",
    aria_colindex = "aria-colindex",
    aria_colspan = "aria-colspan",
    aria_controls = "aria-controls",
    aria_current = "aria-current",
    aria_describedby = "aria-describedby",
    aria_description = "aria-description",
    aria_details = "aria-details",
    aria_disabled = "aria-disabled",
    aria_dropeffect = "aria-dropeffect",
    aria_errormessage = "aria-errormessage",
    aria_expanded = "aria-expanded",
    aria_flowto = "aria-flowto",
    aria_grabbed = "aria-grabbed",
    aria_haspopup = "aria-haspopup",
    aria_hidden = "aria-hidden",
    aria_invalid = "aria-invalid",
    aria_keyshortcuts = "aria-keyshortcuts",
    aria_label = "aria-label",
    aria_labelledby = "aria-labelledby",
    aria_live = "aria-live",
    aria_modal = "aria-modal",
    aria_multiline = "aria-multiline",
    aria_multiselectable = "aria-multiselectable",
    aria_orientation = "aria-orientation",
    aria_owns = "aria-owns",
    aria_placeholder = "aria-placeholder",
    aria_posinset = "aria-posinset",
    aria_pressed = "aria-pressed",
    aria_readonly = "aria-readonly",
    aria_relevant = "aria-relevant",
    aria_required = "aria-required",
    aria_roledescription = "aria-roledescription",
    aria_rowcount = "aria-rowcount",
    aria_rowindex = "aria-rowindex",
    aria_rowspan = "aria-rowspan",
    aria_selected = "aria-selected",
    aria_setsize = "aria-setsize",
    aria_sort = "aria-sort",
    aria_valuemax = "aria-valuemax",
    aria_valuemin = "aria-valuemin",
    aria_valuenow = "aria-valuenow",
    aria_valuetext = "aria-valuetext",
    r#as = "as",
    r#async = "async",
    attributionsrc,
    autocapitalize,
    autocomplete,
    autofocus,
    autoplay,
    blocking,
    capture,
    charset,
    checked,
    cite,
    class,
    closedby,
    cols,
    colspan,
    command,
    commandfor,
    content,
    contenteditable,
    controls,
    controlslist,
    coords,
    crossorigin,
    data,
    datetime,
    decoding,
    default,
    defer,
    dir,
    dirname,
    disabled,
    disablepictureinpicture,
    disableremoteplayback,
    download,
    draggable,
    elementtiming,
    enctype,
    enterkeyhint,
    exportparts,
    fetchpriority,
    r#for = "for",
    form,
    formaction,
    formenctype,
    formmethod,
    formnovalidate,
    formtarget,
    headers,
    height,
    hidden,
    high,
    href,
    hreflang,
    http_equiv = "http-equiv",
    id,
    imagesizes,
    imagesrcset,
    inert,
    inputmode,
    integrity,
    is,
    ismap,
    itemid,
    itemprop,
    itemref,
    itemscope,
    itemtype,
    kind,
    label,
    lang,
    list,
    loading,
    r#loop = "loop",
    low,
    max,
    maxlength,
    media,
    method,
    min,
    minlength,
    multiple,
    muted,
    name,
    nomodule,
    nonce,
    novalidate,
    open,
    optimum,
    part,
    pattern,
    ping,
    placeholder,
    playsinline,
    popover,
    popovertarget,
    popovertargetaction,
    poster,
    preload,
    readonly,
    referrerpolicy,
    rel,
    required,
    reversed,
    role,
    rows,
    rowspan,
    sandbox,
    scope,
    selected,
    shape,
    size,
    sizes,
    slot,
    span,
    spellcheck,
    src,
    srcdoc,
    srclang,
    srcset,
    start,
    step,
    style,
    tabindex,
    target,
    title,
    translate,
    r#type = "type",
    usemap,
    value,
    virtualkeyboardpolicy,
    width,
    wrap,
}
